"""Short-horizon per-step digest gate for the LAPDSim1D golden configuration.

The full golden (``baseline_sim1d.py --verify``) re-runs the whole cycle and
compares the SAVED trajectory. That is ~17 min, and it certifies only what
reaches a save: the golden makes millions of interpolation calls between two
consecutive frames, and a change that moves intermediate arithmetic without
moving the saved state is invisible to it. This gate is the complement --
**every accepted step**, for a short horizon:

* the configuration is EXACTLY the golden's, built by
  ``baseline_sim1d.build_baseline_config`` (``default_config()`` + the committed
  stance file ``scripts/stances/g1atrim.toml`` minus its mesh-sized package +
  ``BASELINE_PARAM_OVERRIDES``/``BASELINE_FLAG_OVERRIDES``), so it cannot drift
  away from the golden's config independently;
* the solver is advanced ``DIGEST_STEPS`` accepted steps and the packed
  conservative state ``y`` -- the solver's own source of truth -- is folded into
  a running SHA-256 after EVERY accepted step, at raw ``uint64`` bytes, together
  with that step's ``t`` at raw ``float64`` bytes;
* per-``CHECKPOINT_INTERVAL`` prefixes of that chain are recorded so a failure
  names the 1,000-step window the divergence entered in, rather than only that
  the run moved.

The one deviation from the golden's own pins is ``max_steps_action = "stop"``
(``DIGEST_PARAM_OVERRIDES``): the golden pins ``"raise"`` because there
``max_steps`` is a tripwire, whereas here the cap IS the run length. It changes
what happens AT the cap and nothing before it, so the digested steps are the
golden's own first ``DIGEST_STEPS`` steps.

Usage::

    # regenerate the reference (ONLY inside a reviewed golden recapture)
    python scripts/golden_digest_gate.py --capture

    # the gate: recompute and compare against the committed reference
    python scripts/golden_digest_gate.py

**The reference file ``scripts/baselines/golden_digest_4k.json`` is part of the
GOLDEN FIXTURE FAMILY.** It pins the same configuration as
``production_discharge.npz`` and is therefore invalidated by exactly the same
events: it ROTATES WITH THE GOLDEN, is regenerated by ``--capture`` in the same
reviewed recapture event that recaptures the NPZ, and is touched by no other
route. Never recapture it to make an unexplained mismatch pass -- a mismatch is
the deliverable.

Compiled kernels: ``CABLP_COMPILED_KERNELS`` is accepted rather than refused.
The kernel provenance is RECORDED in the digest record and printed, but it is
deliberately NOT part of the config identity and not compared, because pure and
compiled are bit-exact by construction of the source (CLAUDE.md, certified
2026-08-17) -- so a compiled run must reproduce the pure reference, and a
divergence between them is a real finding this gate should report rather than
excuse.
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np

from cablp.cathode.kernels import PROVENANCE as KERNEL_PROVENANCE
from cablp.solvers._sim1d import LAPDSim1D

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
# The golden's own config-construction path, reused rather than re-implemented:
# a second copy of the layering would be free to drift away from the fixture it
# is supposed to be pinning. ``_json_safe`` is the same coercion the golden
# sidecar records its config with, so the identity hash below is taken over
# exactly the text the sidecar shows a reviewer.
from baseline_sim1d import (  # noqa: E402
    BASELINE_RUN_KWARGS,
    _json_safe,
    build_baseline_config,
)

#: The committed digest reference. Golden fixture family; see the module note.
DEFAULT_REFERENCE = SCRIPT_DIR / "baselines" / "golden_digest_4k.json"

#: Horizon of the gate, in ACCEPTED steps. A cost knob, not physics.
DIGEST_STEPS = 4000

#: Spacing of the recorded chain prefixes, for bisection.
CHECKPOINT_INTERVAL = 1000

#: The gate's one departure from the golden pins -- see the module docstring.
DIGEST_PARAM_OVERRIDES = {"max_steps_action": "stop"}

#: Written into the reference so the file states its own status where it is read.
REFERENCE_HEADER = (
    "GOLDEN FIXTURE FAMILY. This digest reference pins the same configuration "
    "as baselines/production_discharge.npz and rotates with it: it is "
    "regenerated by scripts/golden_digest_gate.py --capture inside the same "
    "reviewed golden recapture event, and by no other route. Never recapture "
    "it to make a mismatch pass."
)

#: Format tag, so a future layout change is legible rather than a silent
#: mismatch on every field at once.
DIGEST_FORMAT = "sim1d-golden-digest-v1"


def _fold(hasher, time_s, y):
    """Fold one accepted step's ``(t, y)`` into ``hasher`` as raw bytes.

    ``y`` goes in at raw ``uint64`` (its float64 bit patterns, not a decimal
    rendering) so the fold sees every bit the solver produced, including the
    ones a printed or rounded comparison would drop. ``t`` goes in as raw
    ``float64`` bytes for the same reason.
    """
    hasher.update(np.float64(time_s).tobytes())
    hasher.update(
        np.ascontiguousarray(y, dtype=np.float64).view(np.uint64).tobytes()
    )


class _StepDigestTracker:
    """Progress tracker that folds the accepted state after every step.

    ``LAPDSim1D`` calls ``update`` from its run loop once per ACCEPTED step
    (rejected attempts never reach it) when ``progress_interval_s`` is 0, which
    is exactly the hook this gate needs. The tracker reads the solver's packed
    state vector directly: ``_y`` IS the accepted, already-floored state the
    next step starts from, and every primitive field is derived from it.
    """

    def __init__(self, checkpoint_interval):
        self.sim = None
        self.checkpoint_interval = int(checkpoint_interval)
        self.hasher = hashlib.sha256()
        self.checkpoints = {}
        self.steps = 0

    def update(self, progress):
        step = int(progress.step)
        _fold(self.hasher, progress.time, self.sim._y)
        self.steps = step
        if self.checkpoint_interval and step % self.checkpoint_interval == 0:
            self.checkpoints[step] = self.hasher.hexdigest()


def config_identity(params, flags):
    """Return the sha256 of the resolved params/flags JSON, sorted keys."""
    payload = json.dumps(
        {"params": _json_safe(params), "flags": _json_safe(flags)},
        sort_keys=True,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def compute_digest(
    params,
    flags,
    steps=DIGEST_STEPS,
    checkpoint_interval=CHECKPOINT_INTERVAL,
    run_kwargs=None,
):
    """Run ``steps`` accepted steps and return the digest record dict.

    ``run_kwargs`` defaults to the golden's own run controls with ``max_steps``
    replaced by ``steps``. Raises ``RuntimeError`` if the run ends before
    ``steps`` accepted steps (a short run's digest is not comparable to a full
    one and must not be reported as a mismatch) or if the trajectory carries no
    frame at ``t = 0``.
    """
    tracker = _StepDigestTracker(checkpoint_interval)
    # The tracker is bound at CONSTRUCTION and start_simulation is called with
    # no tracker of its own. That is deliberate: start_simulation forwards its
    # own progress arguments to the neutral equilibration, which builds a
    # SEPARATE inner solver, so a tracker passed there would digest the
    # equilibration's steps as well. Bound here it sees the plasma run only.
    sim = LAPDSim1D(params, flags, progress_tracker=tracker, progress_interval_s=0.0)
    tracker.sim = sim

    kwargs = dict(BASELINE_RUN_KWARGS if run_kwargs is None else run_kwargs)
    kwargs["max_steps"] = int(steps)
    sim.start_simulation(**kwargs)
    result = sim.get_results()

    if tracker.steps != int(steps):
        raise RuntimeError(
            f"digest run took {tracker.steps} accepted steps, expected "
            f"{steps}: the run ended before the horizon (t_end or an abort "
            "reached first), so its digest is not comparable to a full one"
        )

    time = np.asarray(result.time, dtype=float)
    y = np.asarray(result.y, dtype=float)
    if time.size == 0 or time[0] != 0.0:
        raise RuntimeError(
            "digest run has no saved frame at t=0, so the step-0 checkpoint "
            f"cannot be taken (first saved time is {time[0] if time.size else None})"
        )
    # Step 0 is the state the stepping STARTS from, taken from the run's own
    # t=0 frame (bit-identical to the packed vector the loop begins with). It is
    # a standalone digest rather than a prefix of the chain, which is what makes
    # it useful: a step-0 mismatch says the initial condition moved -- the
    # equilibrated neutral seed or the fresh IC -- and not the stepping.
    initial = hashlib.sha256()
    _fold(initial, time[0], y[0])

    checkpoints = {"0": initial.hexdigest()}
    for step in sorted(tracker.checkpoints):
        checkpoints[str(step)] = tracker.checkpoints[step]

    cells = int(sim.geometry.cells)
    return {
        "header": REFERENCE_HEADER,
        "digest_format": DIGEST_FORMAT,
        "steps": int(steps),
        "checkpoint_interval": int(checkpoint_interval),
        "digest": tracker.hasher.hexdigest(),
        "checkpoints": checkpoints,
        "config_identity": config_identity(params, flags),
        "cells": cells,
        "fields_per_cell": int(y.shape[1] // cells),
        "final_time": float(result.final_time),
        "kernel_provenance": str(KERNEL_PROVENANCE),
    }


def baseline_digest_record(steps=DIGEST_STEPS):
    """Compute the digest record for the golden configuration."""
    params, flags = build_baseline_config(DIGEST_PARAM_OVERRIDES)
    return compute_digest(params, flags, steps=steps)


def capture(reference_path):
    """Compute the digest record and write it as the committed reference."""
    record = baseline_digest_record()
    reference_path = Path(reference_path)
    reference_path.parent.mkdir(parents=True, exist_ok=True)
    reference_path.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n")
    print(
        "digest reference captured: "
        f"{reference_path}, steps={record['steps']}, "
        f"digest={record['digest']}, "
        f"config_identity={record['config_identity']}, "
        f"kernels={record['kernel_provenance']}"
    )
    return 0


def verify(reference_path):
    """Recompute the digest and compare it against the committed reference."""
    reference_path = Path(reference_path)
    if not reference_path.exists():
        print(f"digest gate FAIL: reference missing: {reference_path}")
        return 1
    reference = json.loads(reference_path.read_text())

    record = baseline_digest_record(steps=int(reference["steps"]))
    print(f"digest gate kernels={record['kernel_provenance']}")

    failures = []
    if record["config_identity"] != reference["config_identity"]:
        failures.append(
            "config identity moved: reference "
            f"{reference['config_identity']} vs fresh "
            f"{record['config_identity']} -- the golden CONFIG changed, so the "
            "reference is stale and this is a recapture question, not a "
            "trajectory question"
        )

    reference_checkpoints = reference["checkpoints"]
    first_divergent = None
    for key in sorted(reference_checkpoints, key=int):
        fresh = record["checkpoints"].get(key)
        if fresh != reference_checkpoints[key]:
            first_divergent = key
            failures.append(
                f"first divergent checkpoint: step {key} -- reference "
                f"{reference_checkpoints[key]} vs fresh {fresh}"
            )
            break
    if first_divergent is None and record["digest"] != reference["digest"]:
        failures.append(
            f"final digest differs: reference {reference['digest']} vs fresh "
            f"{record['digest']} (no checkpoint caught it -- check "
            "checkpoint_interval against steps)"
        )

    if failures:
        print(f"digest gate FAIL: steps={record['steps']}, exact=False")
        for line in failures:
            print(f"  {line}")
        return 1
    print(
        f"digest gate OK: steps={record['steps']}, "
        f"digest={record['digest']}, exact=True"
    )
    return 0


def _parse_args(argv):
    parser = argparse.ArgumentParser(
        description=(
            "Short-horizon per-step state-digest gate for the sim1d golden "
            "configuration."
        )
    )
    parser.add_argument(
        "--capture",
        action="store_true",
        help=(
            "Recompute and OVERWRITE the committed digest reference. Golden "
            "fixture family: only inside a reviewed golden recapture."
        ),
    )
    parser.add_argument(
        "--reference",
        default=str(DEFAULT_REFERENCE),
        help="Path to the digest reference JSON.",
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = _parse_args(argv)
    if args.capture:
        return capture(args.reference)
    return verify(args.reference)


if __name__ == "__main__":
    raise SystemExit(main())
